[package]
name = "donatsu_client"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-net = "0.6.0"
wasm-bindgen-futures = "0.4.43"
yew = { git = "https://github.com/yewstack/yew.git", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }
